title: PLUGIN_ADMIN.DEFAULT
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            content:
              type: wysiwyg
              validate:
                type: textarea